Project = FishNet

Sources = ActivationFunction.cpp ConvolutionalLayer.cpp DropoutMask.cpp FeedForwardNetwork.cpp \
	Layer.cpp Tensor.cpp CostFunction.cpp ImageSet.cpp

Dependencies = Utils

include ../build/library.mk
