Project = Classifier

Sources = CIFAR.cpp Classifier.cpp Faces.cpp ImageSetLoader.cpp MNIST.cpp PGM.cpp Trainer.cpp

Dependencies = Utils FishNet

Libraries = pthread

include ../build/application.mk
